my_store/apps/goods/urls.py
from django.urls import path

from . import views

app_name = 'goods'
urlpatterns = [
    path('', views.index, name='home'),
    path('create', views.create, name='create'),
]

my_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('goods.urls')),
    path('goods/', include('goods.urls')),
    path('admin/', admin.site.urls),
]

my_store/apps/goods/models.py
from django.db import models
import datetime


class Good(models.Model):
    UNITS = (
        (1, 'шт.'),
        (2, 'кг.'),
    )

    good_name = models.CharField(verbose_name='наименование товара', max_length=150)
    date_receipt = models.DateField(verbose_name='дата поступления', default=datetime.datetime.now())
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=0, default=0)
    unit = models.IntegerField(verbose_name='единица измерения', choices=UNITS, default=UNITS[0])
    supplier = models.CharField(verbose_name='имя поставщика', max_length=256, blank=True)

    def __str__(self):
        return self.good_name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

my_store/apps/goods/forms.py
from django.forms import ModelForm, TextInput, Textarea, DateInput, DateTimeInput, TimeInput
from .models import Good


class GoodForm(ModelForm):
    class Meta:
        model = Good
        fields = '__all__'
        widgets = {
            "good_name": TextInput(attrs={
                'class': 'form-control'
            })
        }

    def __init__(self, *args, **kwargs):
        super(GoodForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if isinstance(field.widget, TextInput) or \
                    isinstance(field.widget, Textarea) or \
                    isinstance(field.widget, DateInput) or \
                    isinstance(field.widget, DateTimeInput) or \
                    isinstance(field.widget, TimeInput):
                field.widget.attrs.update({'placeholder': field.label})

my_store/apps/goods/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string

from .models import Good
from .forms import GoodForm

def index(request):
    goods_list = Good.objects.all()
    return render(request, 'goods/good_list.html', {'title': 'Главная страница сайта', 'goods_list': goods_list})


def create(request):
    if request.method == 'POST':
        form = GoodForm(request.POST)
        data = save_good_form(request, form, 'goods/good_create.html')
    else:
        data = {
            'form_is_valid': False,
            'html_form': render_to_string('goods/good_create.html', {'form': GoodForm()}, request=request)
        }

    return JsonResponse(data)

def save_good_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            goods = Good.objects.all()
            data['html_good_list'] = render_to_string('goods/partial_goods_list.html', {
                'goods_list': goods
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)

    return data

my_store/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Мой магазин</h5>
      <nav class="my-2 my-md-0 mr-md-3">
          <a class="p-2 text-dark" href="{% url 'goods:home' %}">Главная</a>
      </nav>
    </div>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% block js %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js"></script>
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
    {% endblock %}
</body>
</html>

my_store/templates/goods/form.html
{% load widget_tweaks %}
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
    </div>
{% endfor %}

<!--    <label for="exampleInputEmail1">Email address</label>-->
<!--    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">-->
<!--    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
<!--{{ form.as_p }}-->

my_store/templates/goods/good_create.html
{% block content %}
<p><h3 style="
    padding-left: 10px;
">Добавить товар</h3></p>
<form method="post" action="{% url 'goods:create' %}" class="js-good-create-form">
    {% csrf_token %}
    <div class="modal-body">
        {% include "goods/form.html" %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
        <button type="submit" class="btn btn-primary">Добавить товар</button>
    </div>
</form>
{% endblock %}

my_store/templates/goods/good_list.html
{% extends 'base.html' %}
{% block title %}Список товаров{% endblock %}
{% block content %}

<div id="good-table tbody">
{% include "goods/partial_goods_list.html" %}
</div>

<div style="margin-top: 30px;">
    <button type="button" class="btn btn-info" id="js-button-add" data-url="{% url 'goods:create' %}">Добавить товар</button>
</div>

<div class="modal fade" id="modal-good">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>

{% endblock %}

my_store/templates/goods/partial_goods_list.html
{% if goods_list %}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Название</th>
        <th scope="col">Дата поступления</th>
        <th scope="col">Цена</th>
        <th scope="col">Единица измерения</th>
        <th scope="col">Имя поставщика</th>
    </tr>
    </thead>
    {% for a in goods_list %}
    <tr>
        <td scope="row">{{ a.good_name }}</td>
        <td scope="row">{{ a.date_receipt }}</td>
        <td scope="row">{{ a.price }}</td>
        <td scope="row">{{ a.unit }}</td>
        <td scope="row">{{ a.supplier }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
Список товаров пуст.
{% endif %}